config/routes.rb
MBrowser7::Application.routes.draw do
  get "integrity/", :controller => 'integrity', :action => 'index'
  get "integrity/time_thumb"
  get "integrity/purge_thumb"
  
  post "logs/read_all", :as => 'logs_read_all'
  resources :logs

  resources :views do
    resource :conditions
  end

  match "tagging_room" => 'tagging_room#index', :as => 'tagging_room'

  post "tagging_room/tag"
  post "tagging_room/untag"

  get "tagging_room/find"

  match "tags" => 'tags#index'
  match "tags/:id" => 'tags#show'
  get "movies/row/" => 'movies#row', :as => 'movie_row'
  resources :movies
  match "movies/:id/thumbs" => 'movies#thumbs', :as => 'movie_thumbs'
  match "movies/:id/thumb" => 'movies#thumb', :as => 'movie_thumb'
  match 'dropbox' => 'dropbox#show'
  match 'add' => 'dropbox#add'
  match 'add_all' => 'dropbox#add_all'
  match 'system_files/process_all' => "system_files#process_all", :as => 'process_all_system_file'
  resources :system_files

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.xml
  def index
#    if params[:page]
#      session[:page] = params[:page]
#    end
#    @page = session[:page]
#    @movies = Movie.paginate :page => session[:page], :per_page => 24
    if params[:view].nil? then session[:view] = View.find_by_name('Newest').id end
    m = View.find(session[:view]).get_movies
    @nb_row = (m.count/6).to_i + 1
    @movies = m.paginate :page => params[:page], :per_page => 24

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @movies }
    end
  end

  def row
    m =View.find(session[:view]).get_movies
    @nb = m.count
    @movies = m.paginate :page => params[:page], :per_page => 6
    respond_to do |format|
      format.html {render 'row',:layout => false}
      format.xml  { render :xml => @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.xml
  def show
    @movie = Movie.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @movie }
      format.js {
      }
    end
  end

  def thumbs
    @movie = Movie.includes(:thumbnails).find(params[:id])
    render :partial => 'thumbnails'
  end

  def thumb
    @movie = Movie.find(params[:id])
    render :partial => 'movie', :locals =>{:movie => @movie}, :layout => false
  end

  # GET /movies/new
  # GET /movies/new.xml
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.xml
  def create
    @movie = Movie.new(params[:movie])
    @movie.name = @movie.system_files.first.original_name
    @movie.delay.generate_thumbnail
    respond_to do |format|
      if @movie.save
        format.html { redirect_to(@movie, :notice => 'Movie was successfully created.') }
        format.xml  { render :xml => @movie, :status => :created, :location => @movie }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.xml
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to(edit_movie_path(@movie), :notice => 'Movie was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @movie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.xml
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to(movies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_bar.erb
<h3><%= unless controller.controller_name == "movies" then  link_to "Movies", :controller => "movies", :action => "index" else render :inline => "<b>Movies</b>" end %></h3>

app/views/movies/_form.html.erb
<% semantic_form_for @movie do |form| %>
    <% form.inputs do %>
    <%= form.input :description %>
    <% if @movie.system_file.nil? %>
    <%= form.input :system_file,
                   :as => :check_boxes,
                   :collection => Hash[SystemFile.where(:storable_id => nil).collect{|f| [f.original_name, f.id]}]%>
            <% end %>
    <%= form.input :tag_list, :as => :string %>
        <% end %>
    <%= form.buttons :commit %>
<% end %>

app/views/movies/_movie.erb
 <script type="text/javascript" charset="utf-8">
  $(document).ready(function()
    {
       $('#movie_img_<%=movie.id%>').click(function(){
          $('#thumbnails').fadeOut();
        $.ajax({
            type: "GET",
            url: "<%= movie_thumbs_path(movie)%>",
            context: $(this),
           success: function(msg){
             	$('#thumbnails').html(msg).fadeIn();
           }
         });
       });
    });
</script>
<h3 style="text-align:center"><%= link_to truncate(movie.name, :length => 12, :omission => "..."), edit_movie_path(movie) %></h3>
<% unless movie.thumbnails[2].nil? %>
    <a id="movie_img_<%=movie.id%>" href="#" rel="<%= movie_thumbs_path(movie) %>" name="<%= movie.name %>"><%= image_tag("#{movie.thumbnails[2].big_path}", :width => 145, :height => 90) %></a>
<% end %>
<div class="g80 inside">
  <% l = movie.fancy_length %>
  <% unless l[:hour] == "0" %>
      <h2 style="display:inline;margin-left:5px"><%= l[:hour] %></h2>H<br>
  <% end %>
  <% unless l[:min] == "0" %>
      <h2 style="display:inline;margin-left:5px"><%= l[:min] %></h2>M<br>
  <% end %>
  <% unless l[:sec] == "0" %>
      <h2 style="display:inline;margin-left:5px"><%= l[:sec] %></h2>S<br>
  <% end %>
</div>
<div class="g80" style="height:20px">
  <span style="float:right"><%= link_to image_tag("vlc.png"), system_file_path(movie.system_file), :remote => true %></span>
</div>

app/views/movies/_thumbnails.erb
<% @movie.thumbnails.each_with_index do |t, i| %>
    <%= image_tag "#{t.big_path}", :width => 150 %>

<% end %>

app/views/movies/edit.html.erb
<script type="text/javascript">
  jQuery(document).ready(function($) {
   var gallery = $('#thumbs').galleriffic({
        delay:                     3000, // in milliseconds
        numThumbs:                 20, // The number of thumbnails to show page
        preloadAhead:              40, // Set to -1 to preload all images
        enableTopPager:            false,
        enableBottomPager:         true,
        maxPagesToShow:            7,  // The maximum number of pages to display in either the top or bottom pager
        imageContainerSel:         '', // The CSS selector for the element within which the main slideshow image should be rendered
        controlsContainerSel:      '', // The CSS selector for the element within which the slideshow controls should be rendered
        captionContainerSel:       '', // The CSS selector for the element within which the captions should be rendered
        loadingContainerSel:       '', // The CSS selector for the element within which should be shown when an image is loading
        renderSSControls:          true, // Specifies whether the slideshow's Play and Pause links should be rendered
        renderNavControls:         true, // Specifies whether the slideshow's Next and Previous links should be rendered
        playLinkText:              'Play',
        pauseLinkText:             'Pause',
        prevLinkText:              'Previous',
        nextLinkText:              'Next',
        nextPageLinkText:          'Next &rsaquo;',
        prevPageLinkText:          '&lsaquo; Prev',
        enableHistory:             false, // Specifies whether the url's hash and the browser's history cache should update when the current slideshow image changes
        enableKeyboardNavigation:  true, // Specifies whether keyboard navigation is enabled
        autoStart:                 false, // Specifies whether the slideshow should be playing or paused when the page first loads
        syncTransitions:           false, // Specifies whether the out and in transitions occur simultaneously or distinctly
        defaultTransitionDuration: 1000, // If using the default transitions, specifies the duration of the transitions
        onSlideChange:             undefined, // accepts a delegate like such: function(prevIndex, nextIndex) { ... }
        onTransitionOut:           undefined, // accepts a delegate like such: function(slide, caption, isSync, callback) { ... }
        onTransitionIn:            undefined, // accepts a delegate like such: function(slide, caption, isSync) { ... }
        onPageTransitionOut:       undefined, // accepts a delegate like such: function(callback) { ... }
        onPageTransitionIn:        undefined, // accepts a delegate like such: function() { ... }
        onImageAdded:              undefined, // accepts a delegate like such: function(imageData, $li) { ... }
        onImageRemoved:            undefined  // accepts a delegate like such: function(imageData, $li) { ... }
    });
  });
</script>
<h1>Editing movie</h1>

<%= render 'form' %>
<%= render 'thumbnails', :local => @movie %>


<div id="controls"></div>
<div id="loading"></div>
<div id="slideshow"></div>
<div id="caption"></div>
<div id="thumbs">
    <ul class="thumbs noscript">
      <% @movie.thumbnails.each_with_index do |t, i| %>
        <li>
            <a class="thumb" href="<%= system_file_path(t.system_files[0]).html_safe %>" title="your image title">
                <%= image_tag "#{t.big_path}", :width => 150 %>
            </a>
          <div class="caption">
                (Any html can go here)
            </div>
        </li>
        <% end %>
    </ul>
</div>


 <a href="<%="file:///"+File.expand_path(@movie.system_file.path)%>" target ="_blank">Open <%= @movie.system_file.name  %></a>
    <%= link_to 'Open in VLC', system_file_path(@movie.system_file), :remote => true %>

<%= link_to 'Destroy', @movie, :confirm => 'Are you sure?', :method => :delete %>

<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        //updatestatus();
        makeButtons();
        scrollalert();

    });

    function makeButtons(){
        $('#speed_normal').button();
        $('#speed_normal').button('disable');
        $('#speed_normal').click(function(){
           scrolloffset = 100;
           $('#speed_normal').button('disable');
           $('#speed_fast').button('enable');
            $('#speed_faster').button('enable');
        });

        $('#speed_fast').button();
        $('#speed_fast').click(function(){
           scrolloffset = 800;
            $('#speed_normal').button('enable');
           $('#speed_fast').button('disable');
            $('#speed_faster').button('enable');
        });

        $('#speed_faster').button();
        $('#speed_faster').click(function(){
           scrolloffset = 1600;
           $('#speed_normal').button('enable');
           $('#speed_fast').button('enable');
            $('#speed_faster').button('disable');
        });
    }
    //var totalItems=<%= @page.to_i*4 %>;
    var nb_loaded_items = 0;
    var last_loaded_row = 0;
    var scrolloffset = 100;
    var loading_lock = 0;
    var nb_row =<%= @nb_row%>;
    function scrollalert() {
        var scrolltop = $(document).scrollTop();
        //alert(scrolltop);
        var scrollheight = $('#content').attr('scrollHeight');
        //alert(scrollheight);
        var windowheight = $(window).height();
        //alert(windowheight);

        if (scrolltop >= (scrollheight - (windowheight + scrolloffset))&& !loading_lock ) {
            //fetch new items
            //$('#status').text('Loading more items...');
            $.ajax({
                type: "GET",
                url: '<%= movie_row_path %>',
                data: "page=" + (++last_loaded_row),
                context: $(this),
                success: function(msg) {
                    s = msg
                    if (last_loaded_row >= 3) {
                        $('.main').animate({height:'+=200'}, 2000);
                    }
                    $('#content').append(s);

                    //loading_lock = true;
                    //totalItems += 1;
                    //updatestatus();
                }
            });
        }
        if (last_loaded_row < nb_row) {
            setTimeout('scrollalert();', 1500);
        }
    }
</script>

<h1>Listing movies</h1>
<div  style="float:right"><b>Loading: </b><button id="speed_normal">Normal</button><button id="speed_fast">Fast</button><button id="speed_faster">Faster</button>
 | <span id="status"></span></div>

<%= link_to 'Skip 120', movies_path(:offset=>20) %>
<div class="clear"></div>
<div id="content">
</div>




<div class="clear"></div>
<%= will_paginate @movies %>
<div class="clear"></div>
<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/row.html.erb
<% @movies.each_with_index do |movie,i| %>

    <script type="text/javascript" charset="utf-8">
    function updatestatus(){
	//Show number of loaded items
	    $('#status').text('Loaded '+ nb_loaded_items +' Items');
    }
    $(document).ready(function()
    {
        $("#<%= movie.id %>").hide();

        //$("#<%= movie.id %>").html('<%= image_tag "loading.gif", :width =>130 %>');
        $.ajax({
            type: "GET",
            url: "<%= movie_thumb_path(movie)%>",
            context: $(this),
           success: function(msg){
             	$("#<%= movie.id %>").html(msg).fadeIn();
               nb_loaded_items += 1;
               updatestatus();
               //<%=if i==@movies.count-1 then 'loading_lock = false;' end%>
           }
         });
    });
      </script>

    <div id="<%= movie.id %>" class="g160 <%=if i==0 then ' inside' end%> rounded-corners ui-widget-content" style="height:200px<%=if i==0 then ';margin-left:0px;' end%>">

    </div>

<% end %>
<div class="clear">&nbsp;</div>

app/views/movies/show.html.erb
<script type="text/javascript">
   var gallery = $('#thumbs').galleriffic({
        delay:                     3000, // in milliseconds
        numThumbs:                 20, // The number of thumbnails to show page
        preloadAhead:              40, // Set to -1 to preload all images
        enableTopPager:            false,
        enableBottomPager:         true,
        maxPagesToShow:            7,  // The maximum number of pages to display in either the top or bottom pager
        imageContainerSel:         '', // The CSS selector for the element within which the main slideshow image should be rendered
        controlsContainerSel:      '', // The CSS selector for the element within which the slideshow controls should be rendered
        captionContainerSel:       '', // The CSS selector for the element within which the captions should be rendered
        loadingContainerSel:       '', // The CSS selector for the element within which should be shown when an image is loading
        renderSSControls:          true, // Specifies whether the slideshow's Play and Pause links should be rendered
        renderNavControls:         true, // Specifies whether the slideshow's Next and Previous links should be rendered
        playLinkText:              'Play',
        pauseLinkText:             'Pause',
        prevLinkText:              'Previous',
        nextLinkText:              'Next',
        nextPageLinkText:          'Next &rsaquo;',
        prevPageLinkText:          '&lsaquo; Prev',
        enableHistory:             false, // Specifies whether the url's hash and the browser's history cache should update when the current slideshow image changes
        enableKeyboardNavigation:  true, // Specifies whether keyboard navigation is enabled
        autoStart:                 false, // Specifies whether the slideshow should be playing or paused when the page first loads
        syncTransitions:           false, // Specifies whether the out and in transitions occur simultaneously or distinctly
        defaultTransitionDuration: 1000, // If using the default transitions, specifies the duration of the transitions
        onSlideChange:             undefined, // accepts a delegate like such: function(prevIndex, nextIndex) { ... }
        onTransitionOut:           undefined, // accepts a delegate like such: function(slide, caption, isSync, callback) { ... }
        onTransitionIn:            undefined, // accepts a delegate like such: function(slide, caption, isSync) { ... }
        onPageTransitionOut:       undefined, // accepts a delegate like such: function(callback) { ... }
        onPageTransitionIn:        undefined, // accepts a delegate like such: function() { ... }
        onImageAdded:              undefined, // accepts a delegate like such: function(imageData, $li) { ... }
        onImageRemoved:            undefined  // accepts a delegate like such: function(imageData, $li) { ... }
    });
</script>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @movie.name %>
</p>

<p>
  <b>Length:</b>
  <%= @movie.length %>
</p>

<p>
  <b>Description:</b>
  <%= @movie.description %>
</p>

<p>
  <b>Thumbnails:</b>

<% @movie.thumbnails.each_with_index do |t, i| %>
    <% if i%5 == 0 %>
        </br>
    <% end %>
    <%= image_tag "#{t.big_path}", :width => 150 %>

    <% end %>
  </p>
</br>
<%= link_to 'Regenerate', movie_path(@movie, :regenerate => true), :remote => true %>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>