config/routes.rb
MBrowser7::Application.routes.draw do
  get "integrity/", :controller => 'integrity', :action => 'index'
  get "integrity/time_thumb"
  get "integrity/purge_thumb"
  
  post "logs/read_all", :as => 'logs_read_all'
  resources :logs

  resources :views do
    resource :conditions
  end

  match "tagging_room" => 'tagging_room#index', :as => 'tagging_room'

  post "tagging_room/tag"
  post "tagging_room/untag"

  get "tagging_room/find"

  match "tags" => 'tags#index'
  match "tags/:id" => 'tags#show'
  get "movies/row/" => 'movies#row', :as => 'movie_row'
  resources :movies
  match "movies/:id/thumbs" => 'movies#thumbs', :as => 'movie_thumbs'
  match "movies/:id/thumb" => 'movies#thumb', :as => 'movie_thumb'
  match 'dropbox' => 'dropbox#show'
  match 'add' => 'dropbox#add'
  match 'add_all' => 'dropbox#add_all'
  match 'system_files/process_all' => "system_files#process_all", :as => 'process_all_system_file'
  resources :system_files

end

app/views/views/_bar.erb
<h5>Views</h5>
<% View.all.each do |v| %>
<div><%= link_to v.name, view_path(v) %></div>
<% end %>

app/views/views/_form.html.erb
<% semantic_form_for @view do |form| %>
    <% form.inputs do %>
        <%= form.input :name %>
        <%= form.input :tag_list, :as => :string %>
        <%= form.inputs :kind, :attr,:name => 'Conditions #%i', :for => :conditions %>
    <% end %>
        <%= form.buttons %>
<% end %>

app/views/views/edit.html.erb
<h1>Editing view</h1>

<%= render 'form' %>

<%= link_to 'Show', @view %> |
<%= link_to 'Back', views_path %>

app/views/views/index.html.erb
<h1>Listing views</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @views.each do |view| %>
  <tr>
    <td><%= view.name %></td>
    <td><%= link_to 'Show', view %></td>
    <td><%= link_to 'Edit', edit_view_path(view) %></td>
    <td><%= link_to 'Destroy', view, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New View', new_view_path %>

app/views/views/new.html.erb
<h1>New view</h1>

<%= render 'form' %>

<%= link_to 'Back', views_path %>

app/views/views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @view.name %>
</p>


<%= link_to 'Edit', edit_view_path(@view) %> |
<%= link_to 'Back', views_path %>