config/routes.rb
MBrowser7::Application.routes.draw do
  get "integrity/", :controller => 'integrity', :action => 'index'
  get "integrity/time_thumb"
  get "integrity/purge_thumb"
  
  post "logs/read_all", :as => 'logs_read_all'
  resources :logs

  resources :views do
    resource :conditions
  end

  match "tagging_room" => 'tagging_room#index', :as => 'tagging_room'

  post "tagging_room/tag"
  post "tagging_room/untag"

  get "tagging_room/find"

  match "tags" => 'tags#index'
  match "tags/:id" => 'tags#show'
  get "movies/row/" => 'movies#row', :as => 'movie_row'
  resources :movies
  match "movies/:id/thumbs" => 'movies#thumbs', :as => 'movie_thumbs'
  match "movies/:id/thumb" => 'movies#thumb', :as => 'movie_thumb'
  match 'dropbox' => 'dropbox#show'
  match 'add' => 'dropbox#add'
  match 'add_all' => 'dropbox#add_all'
  match 'system_files/process_all' => "system_files#process_all", :as => 'process_all_system_file'
  resources :system_files

end

app/views/movies.bak/index.html.erb
<script type="text/javascript" charset="utf-8">
$(document).ready(function()
{
    $('#content a[rel]').each(function()
   {
      $(this).qtip(
      {
         content: {
            // Set the text to an image HTML string with the correct src URL to the loading image you want to use
            text: '<img class="throbber" src="/projects/qtip/images/throbber.gif" alt="Loading..." />',
            url: $(this).attr('rel'), // Use the rel attribute of each element for the url to load
            title: {
               text: $(this).attr('name'), // Give the tooltip a title using each elements text
               button: 'Close' // Show a close link in the title
            }
         },
         position: {
            corner: {
               target: 'topMiddle', // Position the tooltip above the link
               tooltip: 'bottomMiddle'
            },
            adjust: {
               screen: true // Keep the tooltip on-screen at all times
            }
         },
         show: {
            when: 'click',
            solo: true // Only show one tooltip at a time
         },
         hide: 'unfocus',
         style: {
            tip: true, // Apply a speech bubble tip to the tooltip at the designated tooltip corner
            border: {
               width: 0,
               radius: 4
            },
            name: 'light', // Use the default light style
            width: 900 // Set the tooltip width
         }
      })
   });
});
  </script>



<h1>Listing movies</h1>
<div id="content">
<% @movies.each_with_index do |movie,i| %>
    <div class="rounded-corners g160 ui-widget-content" style="height:200px">
    <h3 style="text-align:center"><%= link_to truncate(movie.name, :length => 12,:omission =>  "..."), edit_movie_path(movie) %></h3>
      <% unless movie.thumbnails[2].nil? %>
          <a href="#" rel="<%= movie_thumbs_path(movie) %>" name="<%= movie.name %>"><%=  image_tag("#{movie.thumbnails[2].big_path}", :width => 145, :height => 90) %></a>
      <% end %>
      <div class="g80 inside">
        <% l = movie.fancy_length %>
        <% unless l[:hour] == "0" %>
        <h2 style="display:inline;margin-left:5px"><%= l[:hour] %></h2>H<br>
            <% end %>
        <% unless l[:min] == "0" %>
        <h2 style="display:inline;margin-left:5px"><%= l[:min] %></h2>M<br>
            <% end %>
            <% unless l[:sec] == "0" %>
        <h2 style="display:inline;margin-left:5px"><%= l[:sec] %></h2>S<br>
            <% end %>
      </div>
      <div class="g80" style="height:20px">
    <span style="float:right"><%= link_to image_tag("vlc.png"), system_file_path(movie.system_files.first), :remote => true %></span>
      </div>
  </div>
    <% if (i+1)%6 == 0 and i != 0 %>
      <div class="clear">&nbsp;</div>
    <% end %>
<% end %>
</div>

<div class="clear"></div>
<%= will_paginate @movies %>
<div class="clear"></div>
<%= link_to 'New Movie', new_movie_path %>