config/routes.rb
MBrowser7::Application.routes.draw do
  get "integrity/", :controller => 'integrity', :action => 'index'
  get "integrity/time_thumb"
  get "integrity/purge_thumb"
  
  post "logs/read_all", :as => 'logs_read_all'
  resources :logs

  resources :views do
    resource :conditions
  end

  match "tagging_room" => 'tagging_room#index', :as => 'tagging_room'

  post "tagging_room/tag"
  post "tagging_room/untag"

  get "tagging_room/find"

  match "tags" => 'tags#index'
  match "tags/:id" => 'tags#show'
  get "movies/row/" => 'movies#row', :as => 'movie_row'
  resources :movies
  match "movies/:id/thumbs" => 'movies#thumbs', :as => 'movie_thumbs'
  match "movies/:id/thumb" => 'movies#thumb', :as => 'movie_thumb'
  match 'dropbox' => 'dropbox#show'
  match 'add' => 'dropbox#add'
  match 'add_all' => 'dropbox#add_all'
  match 'system_files/process_all' => "system_files#process_all", :as => 'process_all_system_file'
  resources :system_files

end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :loggable, :polymorphic => true
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  # GET /logs
  # GET /logs.xml
  def index
    @logs = Log.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @logs }
    end
  end

  # GET /logs/1
  # GET /logs/1.xml
  def show
    @log = Log.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @log }
    end
  end

  def read_all
    Log.all.each do |l|
      l.read = true
      l.save!
    end
    render :nothing=>true
  end

  # GET /logs/new
  # GET /logs/new.xml
  def new
    @log = Log.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @log }
    end
  end

  # GET /logs/1/edit
  def edit
    @log = Log.find(params[:id])
  end

  # POST /logs
  # POST /logs.xml
  def create
    @log = Log.new(params[:log])

    respond_to do |format|
      if @log.save
        format.html { redirect_to(@log, :notice => 'Log was successfully created.') }
        format.xml  { render :xml => @log, :status => :created, :location => @log }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @log.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /logs/1
  # PUT /logs/1.xml
  def update
    @log = Log.find(params[:id])

    respond_to do |format|
      if @log.update_attributes(params[:log])
        format.html { redirect_to(@log, :notice => 'Log was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @log.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.xml
  def destroy
    @log = Log.find(params[:id])
    @log.destroy

    respond_to do |format|
      format.html { redirect_to(logs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_accordion_report.erb
<script>
  $(document).ready(function()
{
          $("#accordion").accordion({
              autoHeight: false
          });
          //$("#accordion").accordion('activate',1);


      $('#read_all_link').button();
      $('#read_all_link').click(function(){
          $.ajax({
            type: "POST",
            url: "<%= logs_read_all_path%>",
            context: $(this),
           success: function(msg){
               /**$.get('<%= logs_path %>', function(data) {

                 $('#logs_report').fadeOut();
                 $('#logs_report').html(data);
                 $('#logs_report').fadeIn()
               });**/
                $('#read_all_link').fadeOut();
           }
          });
      });
    });
  </script>
  <div id="accordion">
    <h5 id="read_all_pane"><a href="#">Mark all as read</a></h5>
    <div >
        <button id="read_all_link">Confirm</button>
    </div>
    <% Log.includes(:loggable).where(:read => false).limit(amount-1).each do |l| %>
        <h5><a href="#"><%= truncate(l.title, :length => 35, :omission => "...") %></a></h5>

        <div class="inside" style="padding-left:5px;padding-right:5px;">

            <b>Controller</b><br>
            <%= l.controller %>
            <div class="clear"></div>
            <b>Action</b><br>
            <%= l.action %>
            <div class="clear"></div>
            <b>Description</b><br>
            <%= l.title %>
            <div class="clear"></div>
            <% if l.loggable_type == "Movie" %>
                <%= link_to l.loggable.name, movie_path(l.loggable) %>
              <% else if l.loggable_type == "Thumbnail" %>
                <%= link_to l.loggable.tnable.name, movie_path(l.loggable.tnable) %>
             <% end %>
              <% end %>

        </div>
    <% end %>
  </div>

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :controller %><br />
    <%= f.text_field :controller %>
  </div>
  <div class="field">
    <%= f.label :action %><br />
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :loggable_type %><br />
    <%= f.text_field :loggable_type %>
  </div>
  <div class="field">
    <%= f.label :loggable_id %><br />
    <%= f.text_field :loggable_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<h1>Listing logs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Controller</th>
    <th>Action</th>
    <th>Loggable type</th>
    <th>Loggable</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @logs.each do |log| %>
  <tr>
    <td><%= log.title %></td>
    <td><%= log.controller %></td>
    <td><%= log.action %></td>
    <td><%= log.loggable_type %></td>
    <td><%= log.loggable_id %></td>
    <td><%= link_to 'Show', log %></td>
    <td><%= link_to 'Edit', edit_log_path(log) %></td>
    <td><%= link_to 'Destroy', log, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @log.title %>
</p>

<p>
  <b>Controller:</b>
  <%= @log.controller %>
</p>

<p>
  <b>Action:</b>
  <%= @log.action %>
</p>

<p>
  <b>Loggable type:</b>
  <%= @log.loggable_type %>
</p>

<p>
  <b>Loggable:</b>
  <%= @log.loggable_id %>
</p>


<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>